"""Added market_product indexes to RawCompany

Revision ID: 7374ed324081
Revises: a1b251d9ae27
Create Date: 2025-02-12 22:58:17.960272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7374ed324081'
down_revision: Union[str, None] = 'a1b251d9ae27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_raw_companies_market_product'), 'raw_companies', ['market_product'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_companies_market_product'), table_name='raw_companies')
    # ### end Alembic commands ###
