"""Added indexes to RawCompany

Revision ID: a1b251d9ae27
Revises: f80f5d3e8088
Create Date: 2025-02-12 22:57:10.748791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b251d9ae27'
down_revision: Union[str, None] = 'f80f5d3e8088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('code', table_name='raw_companies')
    op.create_index(op.f('ix_raw_companies_code'), 'raw_companies', ['code'], unique=True)
    op.create_index(op.f('ix_raw_companies_created_at'), 'raw_companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_raw_companies_date'), 'raw_companies', ['date'], unique=False)
    op.create_index(op.f('ix_raw_companies_modified_at'), 'raw_companies', ['modified_at'], unique=False)
    op.create_index(op.f('ix_raw_companies_name'), 'raw_companies', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_companies_name'), table_name='raw_companies')
    op.drop_index(op.f('ix_raw_companies_modified_at'), table_name='raw_companies')
    op.drop_index(op.f('ix_raw_companies_date'), table_name='raw_companies')
    op.drop_index(op.f('ix_raw_companies_created_at'), table_name='raw_companies')
    op.drop_index(op.f('ix_raw_companies_code'), table_name='raw_companies')
    op.create_index('code', 'raw_companies', ['code'], unique=True)
    # ### end Alembic commands ###
