"""Reinitialize migrations

Revision ID: edfb75ad0fc2
Revises: 
Create Date: 2025-02-12 21:15:09.673630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edfb75ad0fc2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('market_product', sa.String(length=255), nullable=False),
    sa.Column('industry33_code', sa.Integer(), nullable=True),
    sa.Column('industry33_category', sa.String(length=255), nullable=True),
    sa.Column('industry17_code', sa.Integer(), nullable=True),
    sa.Column('industry17_category', sa.String(length=255), nullable=True),
    sa.Column('size_code', sa.Integer(), nullable=True),
    sa.Column('size_category', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('bs_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('current_assets', sa.Float(), nullable=True),
    sa.Column('cash_and_cash_equivalents', sa.Float(), nullable=True),
    sa.Column('accounts_receivable', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Float(), nullable=True),
    sa.Column('fixed_assets', sa.Float(), nullable=True),
    sa.Column('tangible_fixed_assets', sa.Float(), nullable=True),
    sa.Column('intangible_fixed_assets', sa.Float(), nullable=True),
    sa.Column('investments_other_assets', sa.Float(), nullable=True),
    sa.Column('current_liabilities', sa.Float(), nullable=True),
    sa.Column('accounts_payable', sa.Float(), nullable=True),
    sa.Column('short_term_loans_payable', sa.Float(), nullable=True),
    sa.Column('non_current_liabilities', sa.Float(), nullable=True),
    sa.Column('bonds_payable', sa.Float(), nullable=True),
    sa.Column('long_term_loans_payable', sa.Float(), nullable=True),
    sa.Column('net_assets', sa.Float(), nullable=True),
    sa.Column('capital_stock', sa.Float(), nullable=True),
    sa.Column('retained_earnings', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pl_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('cost_of_goods_sold', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('selling_general_admin_expenses', sa.Float(), nullable=True),
    sa.Column('operating_profit', sa.Float(), nullable=True),
    sa.Column('non_operating_income', sa.Float(), nullable=True),
    sa.Column('non_operating_expenses', sa.Float(), nullable=True),
    sa.Column('ordinary_profit', sa.Float(), nullable=True),
    sa.Column('extraordinary_income', sa.Float(), nullable=True),
    sa.Column('extraordinary_losses', sa.Float(), nullable=True),
    sa.Column('profit_before_tax', sa.Float(), nullable=True),
    sa.Column('corporate_taxes', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pl_data')
    op.drop_table('bs_data')
    op.drop_table('raw_companies')
    op.drop_table('company')
    # ### end Alembic commands ###
